rootProject.name = "p3-services"
include("p3-gateway")
include("p3-security")
include("p3-signal-bridge")
include("p3-signal-bridge:p3-signal-bridge-activator")
include("p3-service-package")
include("p3-service-package:p3-service-package-adapter")
include("p3-service-package:p3-service-package-application")
include("p3-service-package:p3-service-package-domain")
include("p3-service-package:p3-service-package-infrastructure")
