server:
  port: 8901

spring:
  application:
    name: p3-service-package

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  profiles:
    include:
      - datasource
      - springdoc

logging:
  config: classpath:logback-dev.xml
  level:
    org.springframework: info